---
# vim: set ft=ansible:

- hosts: vsbmc
  gather_facts: true

  vars:
    vsbmc_image: 10

  tasks:
    - name: Install required base packages
      ansible.builtin.dnf:
        name:
          - podman
        state: latest
      become: true

    - name: Setup ${HOME}/vsbmc path
      ansible.builtin.file:
        path: ${HOME}/vsbmc
        state: directory
        mode: 0777
      run_once: true

    # TODO: yes this is garbage
    - name: Configure podman to run vsbmc
      ansible.builtin.shell: |
        podman rm vsbmc --force
        podman run \
          -d \
          --name vsbmc \
          -v "${HOME}/vsbmc:/vsbmc:z" \
          -p "6240:6240/udp" \
          -p "6241:6241/udp" \
          -p "6242:6242/udp" \
          -p "6243:6243/udp" \
          -p "6244:6244/udp" \
          -p "6245:6245/udp" \
          -p "6246:6246/udp" \
            ghcr.io/kurokobo/vbmc4vsphere:0.1.0
      failed_when: false


- hosts: baremetal
  gather_facts: false

  tasks:
    - name: Setup vsbmc emulators
      ansible.builtin.shell: |
        podman exec -it vsbmc \
          vsbmc add {{ inventory_hostname }} \
          --port {{ ipmi_port }} \
          --viserver {{ vcenter_host }} \
          --viserver-username {{ vcenter_user }} \
          --viserver-password {{ vcenter_pass }} \
          --username {{ ipmi_user }} \
          --password {{ ipmi_pass }}
        
        podman exec -it vsbmc \
          vsbmc start {{ inventory_hostname }}
      delegate_to: vsbmc

    - name: Setup firewall to allow vsbmc
      ansible.builtin.shell: |
        firewall-cmd --add-port={{ ipmi_port }}/udp --permanent
        firewall-cmd --reload
      become: true
      delegate_to: vsbmc
